### ISSUE TITLE
有關美好當下

### ISSUE THREAD

**Issue by chenjianrui** [BlingRomance/wedding_LINE_Bot#1]
請問這邊你是怎麼做到讓文字可以即時到照片輪播上的？
我不懂 python 但我看起來你的做法是放到資料庫裡
再由前端去撈嗎？

我最近也在研究用 line bot 寫個婚禮遊戲
但寫的不太順
再麻煩你了
謝謝

**Comment by BlingRomance** [comment]
照片 -> Line Bot -> imgur

視窗程式的 -> imgur -> 輪播
